import type { Express } from "express";
import authRoutes from "./routes/auth.js";
import locationsRoutes from "./routes/locations.js";
import posRoutes from "./routes/pos.js";
import menuRoutes from "./routes/menu.js";
import ingredientsRoutes from "./routes/ingredients.js";
import suppliersRoutes from "./routes/suppliers.js";
import invoicesRoutes from "./routes/invoices.js";
import salesRoutes from "./routes/sales.js";
import forecastRoutes from "./routes/forecast.js";
import schedulesRoutes from "./routes/schedules.js";
import inventoryRoutes from "./routes/inventory.js";
import prepRoutes from "./routes/prep.js";
import anomaliesRoutes from "./routes/anomalies.js";
import recommendationsRoutes from "./routes/recommendations.js";
import actionsRoutes from "./routes/actions.js";
import guestsRoutes from "./routes/guests.js";
import segmentsRoutes from "./routes/segments.js";
import campaignsRoutes from "./routes/campaigns.js";
import reservationsRoutes from "./routes/reservations.js";
import reviewsRoutes from "./routes/reviews.js";
import kpisRoutes from "./routes/kpis.js";
import copilotRoutes from "./routes/copilot.js";
import adminRoutes from "./routes/admin.js";

export function registerRoutes(app: Express): void {
  app.use("/api/auth", authRoutes);
  app.use("/api/locations", locationsRoutes);
  app.use("/api/pos", posRoutes);
  app.use("/api/menu", menuRoutes);
  app.use("/api/ingredients", ingredientsRoutes);
  app.use("/api/suppliers", suppliersRoutes);
  app.use("/api/invoices", invoicesRoutes);
  app.use("/api/sales", salesRoutes);
  app.use("/api/forecast", forecastRoutes);
  app.use("/api/schedules", schedulesRoutes);
  app.use("/api/inventory", inventoryRoutes);
  app.use("/api/prep", prepRoutes);
  app.use("/api/anomalies", anomaliesRoutes);
  app.use("/api/recommendations", recommendationsRoutes);
  app.use("/api/actions", actionsRoutes);
  app.use("/api/guests", guestsRoutes);
  app.use("/api/segments", segmentsRoutes);
  app.use("/api/campaigns", campaignsRoutes);
  app.use("/api/reservations", reservationsRoutes);
  app.use("/api/reviews", reviewsRoutes);
  app.use("/api/kpis", kpisRoutes);
  app.use("/api/copilot", copilotRoutes);
  app.use("/api/admin", adminRoutes);
}
